openai:
  apikey : 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
  openai: https://api.openai.com/v1/engines/davinci/completions
spring:
  application:
    name: codewave-backend
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    # store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codewavedb
    username: root
    password: root
  # Redis ??
  # todo ????????????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?

xunfei:
  appid: dec60e28
  apiSecret: MzMzMGFkYjI2MzAyMjk2MjUzMTRhOTRl
  apiKey: b492175e9919700929dca6b5e0f7dace
  hostUrl: https://tts-api.xfyun.cn/v2/tts

