logging:
  level:
    root: INFO  # 设置全局日志级别
    org.springframework.web: WARN  # 例如，将Spring Web的日志级别设置为WARN
#    n.siegmann.epublib.epub.ResourcesLoader: WARN

spring:
  application:
    name: codewave-backend
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    # store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codewavedb
    username: root
    password: root


  servlet:
    multipart:
      # ????
      max-file-size: 10MB
#  rabbitmq:
#    host: localhost
#    port: 5672
#    password: guest
#    username: guest

  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?



management:
  endpoints:
    web:
      exposure:
        include: beans,health,info

audio:
  models:
    openai:
      concurrency: 10
      maxInputLength: 5000
    xunfei:
      concurrency: 5
      maxInputLength: 20
    yash_Scoop:
      concurrency: 1
      maxInputLength: 500000
    yash_Doofenshmirtz:
      concurrency: 1
      maxInputLength: 500000
    yash_Vader:
      concurrency: 1
      maxInputLength: 500000
    yash_Gollum:
      concurrency: 1
      maxInputLength: 500000
    yash_Cowboy:
      concurrency: 1
      maxInputLength: 500000



